print("haii reny");
print("python")
print("wxyz")
print("R")
print("RE")
print("REN")
print("RENY")
print("RENY J")
print("RENY JO")
print("RENY JOS")
print("RENY JOSE")
print("RENY JOSEP")
print("RENY JOSEPH")      
name=input("Enter your name:")
print("welcome"+name)
a=input("enter first number:")
b=input("enter second number:")
c=int(a)+int(b)
print("addition=",c)
d=int(a)-int(b)
print("subtraction=",d)
e=int(a)*int(b)
print("multiplication=",e)
f=int(a)/int(b)
print("division=",f)
